name: "Bug report"
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Step-by-step reproduction
      placeholder: 1) ... 2) ... 3) ...
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs or add images
